name: Approve Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  approve:
    if: github.event.pull_request.merged == false && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Comment on Pull Request
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          await github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: "All tests passed! This PR is ready to be merged."
          });

    - name: Add 'ready-to-merge' label
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          await github.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            labels: ['ready-to-merge']
          });
